### ISSUE TITLE
Broken link to pre-trained model

### ISSUE THREAD

**Issue by aukhanee** [wzgwzg/Multitask_Weather#1]
Hi, I just checked out your code. But I am unable to find the pre-trained models on the internet. The link provided [here](https://pan.baidu.com/s/1pMDE2uv) seems broken. Please address this issue.
Thanks.

**Comment by wzgwzg** [comment]
I can open this link as well as my friends. Please check your network environment or use other network environment and try again. If you still can't open the link, please tell me, I will try to transfer the pre-trained model to other places.

Thanks.

**Comment by aukhanee** [comment]
I used another network environment, I had to use the Baidu download client for windows. My Chinese isn't that great and I tried to make account on Baidu but still I am unable to download. Is it possible that you set some access code to access the dataset. I know the dataset and models are large files and it will be time consuming to transfer them to other places.

**Comment by wzgwzg** [comment]
I have also uploaded the files to MEGA network disk and re-edit my README file, please try again.

Thanks.

**Comment by aukhanee** [comment]
It is downloading from MEGA network disk. Thank you for the response.
